version: '3'
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    # we don't need port mapping for test  
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] # override Dockerfile default command

